### ISSUE TITLE
Server-start error

### ISSUE THREAD

**Issue by neervanbiqs** [dtmilano/CulebraTester2-public#11]
bash <(curl -sL https://git.io/JT5nc) start-server
Security exception: Package com.dtmilano.android.culebratester2 has not requested permission android.permission.CHANGE_CONFIGURATION

java.lang.SecurityException: Package com.dtmilano.android.culebratester2 has not requested permission android.permission.CHANGE_CONFIGURATION
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:379)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:1410)
        at com.android.server.pm.permission.PermissionManagerService.access$900(PermissionManagerService.java:89)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.grantRuntimePermission(PermissionManagerService.java:2099)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:5421)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1836)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:238)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21339)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2807)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3866)
        at android.os.Binder.execTransact(Binder.java:731)

**Comment by neervanbiqs** [comment]
This problem is fixed in Version 2.0.45-alpha
