### ISSUE TITLE
Server-start error

### ISSUE THREAD

**Issue by drawsta** [dtmilano/CulebraTester2-public#29]
😃 ./CulebraTester2-public/culebratester2 start-server

Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 100
 com.android.server.am.ActivityManagerService.handleIncomingUser:14551 android.app.ActivityManager.handleIncomingUser:4753 com.android.server.pm.PackageManagerShellCommand.translateUserId:3853 
        at com.android.server.am.UserController.handleIncomingUser(UserController.java:2745)
        at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:14551)
        at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4753)
        at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3853)
        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1060)
        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:956)
        at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:792)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7061)
        at android.os.Binder.shellCommand(Binder.java:1087)
        at android.os.Binder.onTransact(Binder.java:904)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4368)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7037)
        at android.os.Binder.execTransactInternal(Binder.java:1371)
        at android.os.Binder.execTransact(Binder.java:1310)
⛔️ ERROR: Cannot get the installed packages.

**Comment by dtmilano** [comment]
Haven't seen this error.
Can you provide more info about the context?

**Comment by kunalkapoor** [comment]
We should reopen this. I see the same issue because I have a work profile installed on my phone so I have multiple users. Doing a "pm list packages" tries to list all packages from all users and adb doesn't have permissions to the work profile.

```
> adb shell pm list packages
Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 11
 com.android.server.am.ActivityManagerService.handleIncomingUser:15970 android.app.ActivityManager.handleIncomingUser:5152 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733
        at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892)
        at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15970)
        at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5152)
        at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733)
        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1074)
        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:960)
        at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:800)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:237)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7136)
        at android.os.Binder.shellCommand(Binder.java:1104)
        at android.os.Binder.onTransact(Binder.java:914)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7120)
        at android.os.Binder.execTransactInternal(Binder.java:1380)
        at android.os.Binder.execTransact(Binder.java:1311)
```

```
> adb shell pm list users
Users:
        UserInfo{0:Kunal Kapoor:4c13} running
        UserInfo{11:Work profile:1030} running
        UserInfo{150:Secure Folder:10061030} running
```

The solution to this is to use the default user explicitly. This cannot be done in the adb daemon directly (atleast I don't know how).
```
> adb shell pm list packages --user 0
```
