### ISSUE TITLE
server-start error due to multiple profiles

### ISSUE THREAD

**Issue by kunalkapoor** [dtmilano/CulebraTester2-public#30]
Reopening issue https://github.com/dtmilano/CulebraTester2-public/issues/29

We should reopen the above issue which was closed as the author did not give details. I see the same issue because I have a work profile installed on my phone so I have multiple users. Doing a "pm list packages" tries to list all packages from all users and adb doesn't have permissions to the work profile.

```
> adb shell pm list packages
Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 11
 com.android.server.am.ActivityManagerService.handleIncomingUser:15970 android.app.ActivityManager.handleIncomingUser:5152 com.android.server.pm.PackageManagerShellCommand.translateUserId:3733
        at com.android.server.am.UserController.handleIncomingUser(UserController.java:2892)
        at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:15970)
        at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:5152)
        at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3733)
        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1074)
        at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:960)
        at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:800)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:237)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:7136)
        at android.os.Binder.shellCommand(Binder.java:1104)
        at android.os.Binder.onTransact(Binder.java:914)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4905)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:7120)
        at android.os.Binder.execTransactInternal(Binder.java:1380)
        at android.os.Binder.execTransact(Binder.java:1311)
```

```
> adb shell pm list users
Users:
        UserInfo{0:Kunal Kapoor:4c13} running
        UserInfo{11:Work profile:1030} running
        UserInfo{150:Secure Folder:10061030} running
```

The solution to this is to use the default user explicitly. This cannot be done in the adb daemon directly (atleast I don't know how).
```
> adb shell pm list packages --user 0
```

**Comment by dtmilano** [comment]
Thanks for the detailed info.
Will take a look.

**Comment by dtmilano** [comment]
Try it and let me know.

**Comment by cwke** [comment]
> Try it and let me know.

Had the same issue, the commit 1a2079e fixes it 👍🏻

**Comment by dtmilano** [comment]
Great. Will merge to `master` after some additional testing.

**Comment by kunalkapoor** [comment]
+1. The above commit fixes the issue for me too. Thanks for fixing it.
